name = "ICOW"
uuid = "3f0c05cb-d2a1-4c03-b976-c0e1c11e0dd4"
version = "0.1.0"
authors = ["James Doss-Gollin <jdossgollin@rice.edu>"]

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SimOptDecisions = "8764eb7a-9599-4112-a7c7-9b4115e89f97"

[compat]
Distributions = ">= 0.25"
QuadGK = ">= 2"
SimOptDecisions = ">= 0.1"
julia = "1.10"
